obsidian_entrypoint_path_str: magnus-archives/magnus-archives.md   
site_name: 'the magnus archives'
html_url_prefix: '/magnus-archives'
toggles: 
    process_all: true
    features: 
        styling:
            layout: documentation
        side_pane:
            right_pane:
                enabled: false
