obsidian_entrypoint_path_str: magnus-archives/homepage.md   
site_name: 'the magnus archives'
html_url_prefix: '/magnus-archives'
navbar_links:
    - name: Home
      link: index.html
    - name: Statements
      link: Statements/Statements.html
toggles: 
    process_all: true
    features:
        styling:
            layout: documentation
            max_note_width: 10rem
        tags_page: 
            enabled: false
        create_index_from_dir_structure:
            enabled: false
        side_pane:
            left_pane:
                enabled: false
            right_pane:
                enabled: false
