obsidian_entrypoint_path_str: magnus-archives/magnus-archives.md   
site_name: 'the magnus archives'
html_url_prefix: '/magnus-archives'
toggles: 
    features: 
        styling:
            layout: minimal
        graph:
            enabled: true
        process_all: true
