name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Install dependencies
        run: |
          sudo gem install jekyll bundler
          
      - name: Create Gemfile
        run: |   
          sudo bundle init
          sudo bundle add jekyll
          sudo bundle update

      - name: Build site
        run: |
         
          bundle install
          bundle exec jekyll build

      - name: Deploy to gh-pages
        run: |
          git clone https://github.com/antivenom03/magnus-archives.git gh-pages
          cd gh-pages
          git checkout gh-pages
          rm -rf *
          cp -r ../_site/* .
          git add .
          git commit -m "Deploy to gh-pages"
          git push origin gh-pages
