name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Install dependencies
        run: |
          sudo gem install jekyll bundler
          
      - name: Create Gemfile
        run: |   
          sudo bundle init
          sudo bundle add jekyll
          sudo bundle update
          bundle install

      - name: Build site
        run: |
          bundle exec jekyll build
         
      - name: I'm in
        run: |
          git config --global user.email jojoivy03@gmail.com
          git config --global user.name Jo
          git remote add repo https://github.com/antivenom03/magnus-archives.git
          git clone --branch gh-pages repo
          cd magnus-archives
          
      - name: get the shit
        run: |
          git pull repo main
 
          
      - name: add
        run: |
          git add .
      - name: commit
        run: |
          git commit -m "Deploy to gh-pages"
      - name: push
        run: |
          git push -u origin gh-pages
